services:
  haproxy:
    image: graph-subscriber/haproxy
    build:
      context: ./haproxy
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        host_ip: 127.0.0.1
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - react
  react:
    image: graph-subscriber/react
    build:
      context: ./react/.devcontainer
      args:
        - VARIANT=16-bullseye
    volumes:
      - .:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
